# TASK 01(diagnostic)

In [1]:
#[1,2,3,4]
a = [1,2,3] 
b = a
b.append(4) 
print(a)

[1, 2, 3, 4]


In [2]:
#false
print(0.1 + 0.2 == 0.3)

False


In [3]:
#wrong predict
g = (x for x in [1,2,3]) 
print(list(g))
print(list(g))

[1, 2, 3]
[]


In [4]:
#[1 4]
#[9 16]

#[7 10]
#[15 22]
import numpy as np
A = np.array([[1,2],[3,4]]) 
print(A * A)
print(A @ A)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [5]:
#[70.  67.5]
m = np.array([[80,70],[60,65]]) 
print(m.mean(axis=0))

[70.  67.5]


In [6]:
#[1,99,3,4,5]
arr = np.array([1,2,3,4,5]) 
s = arr[1:4]
s[0] = 99 
print(arr)

[ 1 99  3  4  5]


In [7]:
#[0.5, 1. , 1.5]
np.array([1,2,3]) / 2

array([0.5, 1. , 1.5])

In [8]:
# np.ones((2,3)) + np.array([1,2]) this give an error

In [9]:
#f(x, items=[]) it give an error

In [10]:
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
import csv
import random
from datetime import datetime, timedelta

random.seed(42)

names=["Abc", "Def", "Xyz", "Pqr", "Aaa"]
domains=["gmail.com", "yahoo.com", "outlook.com"]

data=[]

data.append([
    "roll", "name", "email", "enrolled",
    "exam1", "exam2", "exam3", "exam4"
])

for roll in range(1, 201):

    name=random.choice(names)

    email=name.lower() + str(roll) + "@" + random.choice(domains)

    date=datetime(2026, 1, 1) + timedelta(
        days=random.randint(0, 180)
    )

    enrolled=date.strftime("%Y-%m-%d")

    exam1=random.randint(30, 100)
    exam2=random.randint(30, 100)
    exam3=random.randint(30, 100)
    exam4=random.randint(30, 100)

    if roll==10:
        exam2 = ""

    if roll==50:
        exam3 = ""

    if roll==20:
        email = "wrongemail"

    if roll==30:
        name = name.upper()

    data.append([
        roll, name, email, enrolled,
        exam1, exam2, exam3, exam4
    ])

with open("records.csv", "w", newline="") as f:
    csv.writer(f).writerows(data)

print("records.csv created")

records.csv created


In [13]:
import csv
from collections import Counter, defaultdict
from datetime import datetime


def load_records(path):

    with open(path, "r") as f:
        data = list(csv.DictReader(f))

    print("total students:", len(data))

    domains = []
    wrong_emails = []

    for row in data:

        email = row["email"]

        if "@" in email:
            domain = email.split("@")[1]
            domains.append(domain)
        else:
            wrong_emails.append(row["roll"])

    print("domain count:", Counter(domains))
    print("Wrong email rolls:", wrong_emails)

    for row in data:
        row["name"] = row["name"].strip().title()
    for row in data:
        row["enrolled"] = datetime.strptime(row["enrolled"],"%Y-%m-%d")
    months = []

    for row in data:
        month = row["enrolled"].strftime("%Y-%m")
        months.append(month)

    print("Monthly enrolments:", Counter(months))

    students = defaultdict(list)

    for row in data:
        email = row["email"]
        if "@" in email:
            domain = email.split("@")[1]
            students[domain].append(row)

    print("Students by domain:")

    for domain in students:
        print(domain, len(students[domain]))

    for row in data:
        if row["exam1"] == "":
            row["exam1"] = None

        if row["exam2"] == "":
            row["exam2"] = None

        if row["exam3"] == "":
            row["exam3"] = None

        if row["exam4"] == "":
            row["exam4"] = None

    return data
records = load_records("records.csv")

total students: 200
domain count: Counter({'gmail.com': 77, 'yahoo.com': 65, 'outlook.com': 57})
Wrong email rolls: ['20']
Monthly enrolments: Counter({'2026-06': 47, '2026-05': 42, '2026-04': 35, '2026-03': 30, '2026-02': 23, '2026-01': 23})
Students by domain:
gmail.com 77
yahoo.com 65
outlook.com 57


In [14]:
marks = np.array([
    [
        0 if row["exam1"] is None else int(row["exam1"]),
        0 if row["exam2"] is None else int(row["exam2"]),
        0 if row["exam3"] is None else int(row["exam3"]),
        0 if row["exam4"] is None else int(row["exam4"])
    ]
    for row in records
])
print(marks)
print("Shape:", marks.shape)

student_avg = marks.mean(axis=1)
print("Student average:")
print(student_avg)

exam_avg = marks.mean(axis=0)
print("Exam average:")
print(exam_avg)


passed = student_avg >= 60
print("Passed:", passed.sum())
print("Pass percentage:", passed.mean() * 100)


top10 = np.argsort(student_avg)[-10:][::-1]
print("Top 10:")
print(np.array([records[i]["name"] for i in top10]))
print("Hardest exam:", np.argmin(exam_avg) + 1)

spread = marks.std(axis=0)
print("Widest spread exam:", np.argmax(spread) + 1)

standard = (marks - marks.mean(axis=0)) / marks.std(axis=0)
print("Standardised marks:")
print(standard)

curve = np.minimum(marks + 5, 100)
print("Curved marks:")
print(curve)
print("Marks reached 100:", (curve == 100).sum())

[[ 61  58  47  43]
 [ 84  34  33  41]
 [ 33  55  99  83]
 [ 65  30  50  84]
 [ 57  73  43  41]
 [ 74  63  35  88]
 [ 40 100  67  76]
 [ 38  35  59  67]
 [ 78  65  88  76]
 [ 56   0  39  51]
 [ 50  89  78  64]
 [ 71  37  59  34]
 [ 38  57  70  57]
 [ 88  48  63  47]
 [ 98  63  84  81]
 [ 95  93  41  36]
 [ 50  84  38  79]
 [ 97  62 100  31]
 [ 64  73  44  67]
 [ 30  63  94  52]
 [ 68  94  55  49]
 [ 97  30  71  92]
 [ 69  60  37  60]
 [ 92  38  98  46]
 [100  51  63  97]
 [ 99  55  69  81]
 [ 87  45  61  58]
 [100  59  58  30]
 [ 37  59  38  34]
 [ 60  65  92  57]
 [ 90  61  90  82]
 [ 85  75  84  82]
 [ 42  37  81  73]
 [ 54  98  87  47]
 [ 89  61  39  86]
 [ 99  31  41  60]
 [ 91  57  81  37]
 [ 79  63  88  66]
 [ 92  49  54  67]
 [ 99  37  70  37]
 [ 94  97  50  37]
 [ 38  38  60  81]
 [ 35  40  83  96]
 [ 70  60  63  80]
 [ 68  88  70  39]
 [ 42  39  98  57]
 [ 74  38  61  77]
 [ 99  68  97  31]
 [ 43  47  63  44]
 [ 49  64   0  56]
 [ 63  94  92  62]
 [ 84  65  35  30]
 [ 63  50  8